### ISSUE TITLE
Weird readings in both total yield and today's production 

### ISSUE THREAD

**Issue by udivankin** [gcarmix/azzurrozcs#1]
While Azzurro Monitoring app has adequate readings for total production and today's production, both status.html web gui page and (not surprising) custom integration sensor readings are weird.  For today's yield, my best bet is the timezone. But for total production I have no ideas.

<img width="579" alt="Screenshot 2023-01-18 at 16 15 18" src="https://user-images.githubusercontent.com/1522846/213195671-00f5e9d2-fcce-4f4d-abfa-b8919794f58b.png">
<img width="983" alt="Screenshot 2023-01-18 at 16 13 58" src="https://user-images.githubusercontent.com/1522846/213195680-45d7a6b0-3090-4b7e-a715-577d5fe29306.png">
<img width="976" alt="Screenshot 2023-01-18 at 16 12 27" src="https://user-images.githubusercontent.com/1522846/213195686-fc10b4ff-9801-462a-a0c7-0f5ace21fb8b.png">

please note that these screenshots where made in just 3 minutes

**Comment by gcarmix** [comment]
hi udivankin,
sorry for my late response, I've seen the issue only now, unfortunately I have no guess on why your inverter is returning those data. My only tip is to try to reset the counters from its web interface.
I close this issue since is not related to the integration, but to the inverter interface itself.
