### ISSUE TITLE
Compatiblity error with HomeAssistant 2023.5

### ISSUE THREAD

**Issue by syntesys** [gcarmix/azzurrozcs#4]
Hi, 
with the introduction of SSLCypherList in RestData, the plugin does not start anymore.

I resolved adding the following import at the start of the sensor.py:
from homeassistant.util.ssl import SSLCipherList

and modifying the line:
rest = RestData(hass, method, zcs_address,'utf-8', auth, headers, None, None, verify_ssl, timeout)
with
rest = RestData(hass, method, zcs_address,'utf-8', auth, headers, None, None, verify_ssl, SSLCipherList.PYTHON_DEFAULT, timeout)

Thank you for the plugin!

**Comment by gcarmix** [comment]
Hi @syntesys87 , I just updated the plugin with your observation to fix compatibility with 2023.5. Anyway I slightly modified it by not including the SSLCipherList import because it would break compatibility with older HomeAsssitant versions. 
thank you for your support and if you like the plugin don't forget to star it ;)
